-- Load Install Van stock-count catalog (200 items). Safe to run once.
alter table public.items add column if not exists unit text;
alter table public.items add column if not exists category text;
create index if not exists items_category_idx on public.items (category);

insert into public.items (name, unit, category, min_qty, qty) values
('3/4"x10'' PVC SCH 40 Pipe', 'Stick', 'PVC PIPE & FITTINGS', 3, 0),
('3/4" FPT Adaptor', 'Each', 'PVC PIPE & FITTINGS', 10, 0),
('3/4" MPT Adaptor', 'Each', 'PVC PIPE & FITTINGS', 10, 0),
('3/4" PVC 90* FPT ELL', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('3/4" PVC 90* MPT ELL', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('3/4" PVC 45* ELL', 'Each', 'PVC PIPE & FITTINGS', 10, 0),
('3/4" PVC 90* ELL 100/BX', 'Each', 'PVC PIPE & FITTINGS', 10, 0),
('3/4" PVC Coupling', 'Each', 'PVC PIPE & FITTINGS', 10, 0),
('3/4" PVC TEE', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('3/4" PVC Cap', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('3/4" PVC P-Trap', 'Each', 'PVC PIPE & FITTINGS', 5, 0),
('3/4" CPVC to PVC Adapter', 'Each', 'PVC PIPE & FITTINGS', 2, 0),
('1 1/2" x 3/4" Reducer Bush. PVC', 'Each', 'PVC PIPE & FITTINGS', 1, 0),
('1" 90* PVC ELL', 'Each', 'PVC PIPE & FITTINGS', 1, 0),
('1" PVC Coupling', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('All Access Condensate Clean-out', 'Each', 'PVC PIPE & FITTINGS', 4, 0),
('PVC Rain R Shine Blue Cement', 'Each', 'PVC PIPE & FITTINGS', 2, 0),
('3/8"x50'' Soft Copper', 'Foot', 'COPPER PIPE & FITTINGS', 50, 0),
('1/2"x50'' Soft Copper', 'Foot', 'COPPER PIPE & FITTINGS', 25, 0),
('5/8"x50'' Soft Copper', 'Foot', 'COPPER PIPE & FITTINGS', 25, 0),
('3/4"x50'' Soft Copper', 'Foot', 'COPPER PIPE & FITTINGS', 50, 0),
('7/8"x50'' Soft Copper', 'Foot', 'COPPER PIPE & FITTINGS', 50, 0),
('3/8" Copper Coupling 50/bx', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('1/2" Copper Coupling', 'Each', 'COPPER PIPE & FITTINGS', 5, 0),
('5/8" Copper Coupling', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('3/4" Copper Coupling 25/bx', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('7/8" Copper Coupling 25/bx', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('3/8" Copper L/R 90 ELL', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('1/2" Copper L/R 90 ELL', 'Each', 'COPPER PIPE & FITTINGS', 5, 0),
('5/8" Copper L/R 90 ELL 50/bx', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('3/4" Copper L/R 90 ELL 50/bx', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('7/8" Copper L/R 90 ELL', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('5/8" Copper L/R 90 ST ELL', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('3/4" Copper L/R 90 ST ELL', 'Each', 'COPPER PIPE & FITTINGS', 10, 0),
('7/8" Copper L/R 90 ST ELL 10/bx', 'Each', 'COPPER PIPE & FITTINGS', 4, 0),
('Honeywell F33Cover Plate 1-LG 1-MED', 'Each', 'THERMOSTATS', 2, 0),
('T4', 'Each', 'THERMOSTATS', 1, 0),
('T6', 'Each', 'THERMOSTATS', 1, 0),
('Pro 8000', 'Each', 'THERMOSTATS', 1, 0),
('Trane 1050', 'Each', 'THERMOSTATS', 1, 0),
('Trane XL1050 Communication Touch Screen', 'Each', 'THERMOSTATS', 1, 0),
('MC-10 Acety Contents', 'Each', 'WELDING GASES & REFRIGERANT', 1, 0),
('R-20 Oxygen Contents', 'Each', 'WELDING GASES & REFRIGERANT', 1, 0),
('40 CF- Nitrogen Contents', 'Each', 'WELDING GASES & REFRIGERANT', 2, 0),
('R-410 A Refrigerant 25#', 'Each', 'WELDING GASES & REFRIGERANT', 2, 0),
('5/8"x3/4"x 6'' Armaflex 30/BX', 'Stick', 'ARMAFLEX', 1, 0),
('3/4"x3/4"x6'' Armaflex 24/BX', 'Stick', 'ARMAFLEX', 2, 0),
('7/8"x3/4"x6'' Armaflex 21/BX', 'Stick', 'ARMAFLEX', 2, 0),
('1 1/8"x3/4"x6'' Armaflex 15/BX', 'Stick', 'ARMAFLEX', 0, 0),
('1 1/8"x3/16"x6'' Armaflex 41/bx', 'Stick', 'ARMAFLEX', 2, 0),
('White Armaflex Paint 1 Gallon', 'Each', 'ARMAFLEX', 1, 0),
('20A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('25A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('30A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('35A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('40A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('45A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('50A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('60A2P SQ D Breaker', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('20A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('25A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('30A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('35A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('40A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('45A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('50A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('60A2P SQ Homeline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('20A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('25A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('30A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('35A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('40A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('45A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('50A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('60A2P Murray/Challenger Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('20A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('25A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('30A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('35A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 1, 0),
('40A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 1, 0),
('45A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 1, 0),
('50A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 1, 0),
('60A2P Cutler Hammer Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('20A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('25A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 3, 0),
('30A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('35A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('40A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('45A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('50A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('60A2P GE Slimline Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('20A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('25A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('30A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('35A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('40A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('45A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('50A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('60A2P Federal Pacific Bkr', 'Each', 'ELECTRICAL BREAKERS', 2, 0),
('Small Blue Wire Nuts 100/bx', 'Box', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Orange Wire Nuts 100/bx', 'Box', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Scotchlok UY2', 'Each', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Yellow Wire Nuts 100/bx', 'Box', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Red Wire Nuts 100/bx', 'Box', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Blue Winggard 50/bx', 'Box', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('3.5-5hp Hard Start', 'Each', 'MISCELLANEOUS ELECTRICAL', 2, 0),
('1/2" Rubber Grommets', 'Each', 'MISCELLANEOUS ELECTRICAL', 2, 0),
('Intermatic Surge Protector Type 1 &2', 'Each', 'MISCELLANEOUS ELECTRICAL', 2, 0),
('Vertical Wet Switch', 'Each', 'MISCELLANEOUS ELECTRICAL', 2, 0),
('Transformer 120/240V 24VAC, 40VA', 'Each', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Transformer 120/240v 24VAC, 75VA', 'Each', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Contactor 40A/2P/24V', 'Each', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('3/4" Romex Conn 100/pk', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('1/2" Romex Conn 100/pk', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('1"x1/2" Red. Washer 100/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 12, 0),
('Disconnect 60A Non-Fused', 'Each', 'MISCELLANEOUS ELECTRICAL', 2, 0),
('Disconnect 60A Fused', 'Each', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Fuse AUTO ATC-3 Amp 5/pk', 'Pkg', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('Fuse AUTO ATC-5 Amp 5/pk', 'Pkg', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('1/2"x100'' NON-MET Sealtite', 'Foot', 'MISCELLANEOUS ELECTRICAL', 100, 0),
('3/4" EMT Clamp 100/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 20, 0),
('1" EMT Clamp 100/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 20, 0),
('3/4"x100'' NON-MET Sealtite', 'Foot', 'MISCELLANEOUS ELECTRICAL', 100, 0),
('1/2" STRT PLAST Conn 10/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('3/4" STRT PLAST Conn 10/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('3/4" 90* ELL PLAST FTG 10/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('1/2" 90* ELL PLAST FTG 10/bx', 'Each', 'MISCELLANEOUS ELECTRICAL', 10, 0),
('Romex 10-2 w/GRD 250''/Roll', 'Foot', 'MISCELLANEOUS ELECTRICAL', 250, 0),
('Romex 14-2 w/GRD 250''/Roll', 'Foot', 'MISCELLANEOUS ELECTRICAL', 250, 0),
('Romex 6-2 w/GRD 125''/Roll', 'Foot', 'MISCELLANEOUS ELECTRICAL', 125, 0),
('Romex 8-2 w/GRD 125''/Roll', 'Foot', 'MISCELLANEOUS ELECTRICAL', 125, 0),
('18/8-UL 8 -T-Stat Wire 250''', 'Roll', 'MISCELLANEOUS ELECTRICAL', 1, 0),
('FASSON 0810 UL181A-P Silver Tape', 'Roll', 'TAPES', 8, 0),
('950 2"x 60YD Black Tape', 'Roll', 'TAPES', 2, 0),
('3/4" Electrical Tape', 'Roll', 'TAPES', 1, 0),
('1/8"x2"x30'' Foam tape', 'Roll', 'TAPES', 1, 0),
('1/8"x2"x30'' Cork Tape', 'Roll', 'TAPES', 1, 0),
('Duct Saddle', 'Each', 'TAPES', 25, 0),
('GlassFab 3"x150'' Mastic Tape', 'Roll', 'TAPES', 1, 0),
('Hard Hats - White', 'Each', 'SAFETY & MISC GEAR', 1, 0),
('Safety Glasses', 'Each', 'SAFETY & MISC GEAR', 1, 0),
('Face/Dust Mask 50/bx', 'Each', 'SAFETY & MISC GEAR', 6, 0),
('Ear Plugs 200/bx', 'Each', 'SAFETY & MISC GEAR', 5, 0),
('Construction First Aid Kit Small', 'Each', 'SAFETY & MISC GEAR', 1, 0),
('Shoe Covers 100 / box', 'Box', 'SAFETY & MISC GEAR', 12, 0),
('60" Ladder Safety Strap', 'Pkg', 'SAFETY & MISC GEAR', 4, 0),
('AA Battery', 'Each', 'SAFETY & MISC GEAR', 8, 0),
('AAA Battery', 'Each', 'SAFETY & MISC GEAR', 8, 0),
('9V Battery', 'Each', 'SAFETY & MISC GEAR', 2, 0),
('AG-1100+ Aqua-Guard Secondary Float Switch', 'Each', 'MISCELLANEOUS', 2, 0),
('Condensate Overflow Switch TP - SS2', 'Each', 'MISCELLANEOUS', 2, 0),
('5019-9/16 Staples', 'Pkg', 'MISCELLANEOUS', 1, 0),
('Staple, 5/16" T50 1250/bx Arrow Brand', 'Pkg', 'MISCELLANEOUS', 1, 0),
('Handi-Foam Sealant 12oz 12/cs', 'Each', 'MISCELLANEOUS', 2, 0),
('Spray Adhesive 12/cs', 'Each', 'MISCELLANEOUS', 3, 0),
('Visqueen / Poly sheet (roll)', 'Roll', 'MISCELLANEOUS', 3, 0),
('Vibra Pad 3/4"x16"x16"-2"pcs-64pcs/pad', 'PCS', 'MISCELLANEOUS', 16, 0),
('Wasp spray 14 oz', 'Each', 'MISCELLANEOUS', 1, 0),
('Drain Solve 12/CASE', 'Each', 'MISCELLANEOUS', 3, 0),
('Outdoor Only ALKI-Foam Non Acid', 'Each', 'MISCELLANEOUS', 1, 0),
('Evap Power C', 'Each', 'MISCELLANEOUS', 1, 0),
('Leak Detector 8 0Z', 'Each', 'MISCELLANEOUS', 1, 0),
('15% Silver Solder 28/STK', 'Tube', 'MISCELLANEOUS', 2, 0),
('2" Mastic Brush 24" Long', 'Each', 'MISCELLANEOUS', 2, 0),
('Indoor/Outdoor, White, Paintable, Acrylic Caulk', 'Tube', 'MISCELLANEOUS', 2, 0),
('Silicone Caulk', 'Tube', 'MISCELLANEOUS', 2, 0),
('Sandcloth 10-Yard', 'Each', 'MISCELLANEOUS', 1, 0),
('3/8" Liquid Line Drier R22/410A/4007C', 'Each', 'MISCELLANEOUS', 2, 0),
('Mastic 1 Gallon 4/cs', 'Each', 'MISCELLANEOUS', 4, 0),
('2" Mastic Brush 24/bx', 'Each', 'MISCELLANEOUS', 4, 0),
('Mtg Bkt / Boot Clip 100/bx', 'Box', 'MISCELLANEOUS', 25, 0),
('11" Black Duct Straps 50/bg', 'Bag', 'MISCELLANEOUS', 2, 0),
('Penetrating Spray 12OZ 12/cs', 'Each', 'MISCELLANEOUS', 2, 0),
('36" Cable Strap 50/bg', 'Bag', 'MISCELLANEOUS', 2, 0),
('FlowPlus-25 Replacement Tablets', '25/btl', 'MISCELLANEOUS', 1, 0),
('Appion TEZOM Vacuum Pump Oil', 'Each', 'MISCELLANEOUS', 1, 0),
('4KH7 Blades-6" 6TPI Wood 5/pk', 'Pkg', 'MISCELLANEOUS', 1, 0),
('4TF18 Blades-6" 18 TPI Metal 5/pk', 'Pkg', 'MISCELLANEOUS', 1, 0),
('240V Condensate Pump', 'Each', 'MISCELLANEOUS', 1, 0),
('FS750 Fin Saver 3/4"', 'Each', 'MISCELLANEOUS', 4, 0),
('FS875 Fin Saver 7/8"', 'Each', 'MISCELLANEOUS', 4, 0),
('Refrigerant Safety Cap Key, Universal', 'Each', 'MISCELLANEOUS', 2, 0),
('Refrigerant Safety Caps, Universal', 'Each', 'MISCELLANEOUS', 10, 0),
('Teflon Tape #13229 Roll', 'Roll', 'MISCELLANEOUS', 1, 0),
('Black Web Hanging Strap 24/bx', 'Roll', 'MISCELLANEOUS', 2, 0),
('1"x100''Ft 26 Ga Strap', 'Roll', 'MISCELLANEOUS', 1, 0),
('3/8" Nuts 100/bx', 'Box', 'FASTENERS', 1, 0),
('3/8" Washer 100/bx', 'Box', 'FASTENERS', 1, 0),
('3/8" Coupling Nut 100/bx', 'PCS', 'FASTENERS', 1, 0),
('Tap Con 1/4"x1 1/4" 100/bx', 'Box', 'FASTENERS', 1, 0),
('10x3/4" Selfdrill Tek Screw 500/Bx', 'Box', 'FASTENERS', 1, 0),
('Grille Screws White P/HD 250/bx', 'Box', 'FASTENERS', 1, 0),
('Plastic Wall Anchors', 'Box', 'FASTENERS', 1, 0),
('Drywall Mud', 'Each', 'FASTENERS', 1, 0),
('Drywall Screw 1 1/4"; Course 100/bx', 'Box', 'FASTENERS', 1, 0),
('Grip-Rite 3" Deck Screws 100ct', 'Box', 'FASTENERS', 1, 0),
('1"x6" Angle Brkt 4/pk', 'Pkg', 'FASTENERS', 2, 0),
('3/4"x3/4"x1 5/8" x 10'' Grn Hanging Channel 1.5-3Ton', 'Stick', 'FASTENERS', 1, 0),
('1 5/8" x 1 5/8" x 10'' Grn Hanging Channel 3.5-5Ton', 'Stick', 'FASTENERS', 2, 0),
('3/8" x 6'' All Thread Rod (25 ct)', 'Stick', 'FASTENERS', 4, 0);